artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Abdallah-Ahmed-98/DATASETS/raw/main/Churndataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Churndataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Churndataset.csv
  transformation_pipline_name: transformation_pipline.joblib




model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  confusion_matrix_file_path: artifacts/model_evaluation/confusion_matrix.png
  roc_curve_file_path: artifacts/model_evaluation/roc_curve.png




prediction:
  transformation_pipline_path: artifacts/data_transformation/transformation_pipline.joblib
  model_path: artifacts/model_trainer/model.joblib


